# Generated by Django 5.0.6 on 2024-07-11 10:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
